### ISSUE TITLE
meme nom d'utilisateur

### ISSUE THREAD

**Issue by moKacraft** [moKacraft/slidare_android#8]

**Comment by cintiaf** [comment]
Vérification que le nom d'utilisateur n'existe pas déjà en base.

**Comment by cintiaf** [comment]
Il peut y avoir plusieurs même username en base car c'est e-mail qui permet de différencier les comptes utilisateurs, un peu comme Facebook, il y a beaucoup de Cintia Ferreira mais seulement moi avec mon e-mail.

Donc tâche close.
