### ISSUE TITLE
meme email

### ISSUE THREAD

**Issue by moKacraft** [moKacraft/slidare_android#9]

**Comment by cintiaf** [comment]
Vérifier que l'email n'existe pas déjà.

**Comment by moKacraft** [comment]
c'est trop long comme message

**Comment by cintiaf** [comment]
Il faut vérifier que l'email n'existe pas déjà à 2 endroits :
- lors de la création de compte : erreur déjà fournie par l'API, il faut juste afficher le message d'erreur
- lors de la modification de l'email sur le profil utilisateur : après discussion, ce feature dois être supprimé car il ne devrait pas être possible de modifier l'email utilisateur (ps: pas de requête API existante pour savoir si un email correspond déjà à un compte de toute façon). 

Donc supprimer la modification d'email sur le profil utilisateur.

Commit : https://github.com/moKacraft/slidare_android/commit/7d820cea668f43ab5198227171cc7ad28856b34e
